name: CD 

on:
  push:
    branches:
      - main 

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo del servicio
        uses: actions/checkout@v4

      - name: Extraer ID del commit
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout repo de GitOps
        uses: actions/checkout@v4
        with:
          repository: alejandraRamos/argocd-gitops
          token: ${{ secrets.GITOPS_REPO_TOKEN }} # Se necesita un token con permisos de escritura
          path: gitops-repo

      - name: Actualizar imagen
        run: |
          cd gitops-repo
          sed -i 's|image: alejandraramos/demo:.*|image: alejandraramos/demo:${{ env.SHORT_SHA }}|' apps/demo-app/deployment.yaml

      - name: Commit y Push de cambios
        run: |
          cd gitops-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add apps/demo-app/deployment.yaml
          git commit -m "Update image tag to ${{ env.COMMIT_ID }}"
          git push