name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: demo-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Ensure package-lock.json exists
        run: npm install --package-lock-only
      - name: Install dependencies
        run: npm ci

  build-and-push:
    permissions:
      id-token: write
      contents: read
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586794463771:role/assume-role-github-demo
          aws-region: ${{ env.AWS_REGION }}

      - name: Set short SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag and Push image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY

          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Generate version from commit SHA
      #   run: |
      #     COMMIT_SHA=$(git rev-parse --short HEAD)
      #     echo "VERSION=$COMMIT_SHA" >> $GITHUB_ENV

      # - name: Update HTML with commit ID
      #   run: |
      #     echo "window.commitId = \"${{ env.VERSION }}\";" > ./app.js
      #   env:
      #    COMMIT_ID: ${{ env.VERSION }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: |
      #       alejandraramos/demo:latest
      #       alejandraramos/demo:${{ env.VERSION }}
